PROJECT: SMPL
DATASETS:
    TRAIN:
        H36M:
            DATASET_FILE: mshot_data/regression_data/extras/h36m_train.npz
            IMG_DIR: mshot_data/datasets/h36m/images
            TRAIN: True
            WEIGHT: 0.4
        COCO:
            DATASET_FILE: mshot_data/regression_data/extras/coco_2017_train_spin.npz
            IMG_DIR: mshot_data/datasets/coco
            TRAIN: True
            WEIGHT: 0.15
        MPII:
            DATASET_FILE: mshot_data/regression_data/extras/mpii_train_spin.npz
            IMG_DIR: mshot_data/datasets/mpii_human_pose_v1_u12_2/images
            TRAIN: TRUE
            WEIGHT: 0.15
        AVA:
            DATASET_FILE: mshot_data/regression_data/extras/ava_multi_shot.npz
            IMG_DIR: mshot_data/datasets/ava/train/midframes
            TRAIN: TRUE
            WEIGHT: 0.3
SMPL:
  MODEL_PATH: mshot_data/models/smpl
  GENDER: neutral
  MODEL_TYPE: smpl
  NUM_BODY_JOINTS: 23
  JOINT_REGRESSOR_EXTRA: mshot_data/regression_data/SMPL_to_J19.pkl
GENERAL:
  SUMMARY_STEPS: 100
  CHECKPOINT_STEPS: 10000
  NUM_WORKERS: 12
  USE_CUDA: TRUE

TRAIN:
  LR: 1e-4
  WEIGHT_DECAY: 1e-4
  BATCH_SIZE: 64
  EXTREME_CROPPING: TRUE
LOSS_WEIGHTS:
    KEYPOINTS_2D: 1
    KEYPOINTS_3D: 1
    GLOBAL_ORIENT: 0.1
    BODY_POSE: 0.1
    BETAS: 0.05
    BETA_REG: 0.005
MODEL:
  IMAGE_SIZE: 256
  SMPL_HEAD:
      TYPE: basic
      POOL: max
      SMPL_MEAN_PARAMS: mshot_data/regression_data/smpl_mean_params.npz
      IN_CHANNELS: 2048
  BACKBONE:
    TYPE: resnet
    NUM_LAYERS: 50
EXTRA:
  FOCAL_LENGTH: 5000
